apiVersion: v1
kind: Pod
metadata:
  name: ml-dev-tmp
  labels:
    app: ml-dev
spec:
  #  nodeSelector:
  #    kubernetes.io/hostname: vana
  #  tolerations:
  #    - key: "node.kubernetes.io/unschedulable"
  #      operator: "Equal"
  #      effect: "NoSchedule"
  containers:
    - name: ml-dev
      image: lsx-harbor.informatik.uni-wuerzburg.de/dallmann/recommender:latest
      imagePullPolicy: "Always"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: 1
        limits:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: 1
      command: ["sleep", "365d"]
      env:
        - name: HOME
          value: /home/ls6/dallmann
      volumeMounts:
        - mountPath: /home/ls6/dallmann # directory IN the container
          name: home # matches volume-name from below
        - mountPath: /scratch # directory IN the container
          name: scratch # matches volume-name from below
        - mountPath: /ssd
          name: cache
        - mountPath: /dev/shm
          name: dshm
      ports:
        - containerPort: 8888
  imagePullSecrets:
    - name: lsx-harbor
  restartPolicy: "Never"
  volumes:
    - name: home
      cephfs:
        monitors:
          - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
        user: dallmann  # <namespace>
        path: "/home/ls6/dallmann" # The path you want to mount
        secretRef: # The name of the secret for auth. Is always "ceph-secret"
          name: ceph-secret-dallmann
    - name: scratch
      cephfs:
        monitors:
          - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
        user: dallmann  # <namespace>
        path: "/scratch" # The path you want to mount
        secretRef: # The name of the secret for auth. Is always "ceph-secret"
          name: ceph-secret-dallmann
    - name: cache
      emptyDir: {}
    - name: dshm
      emptyDir:
        medium: Memory

