LOG_KEY_VALIDATION_LOSS = 'val_loss'
LOG_KEY_TEST_LOSS = 'test_loss'
LOG_KEY_TRAINING_LOSS = 'train_loss'

RETURN_KEY_SEQUENCE = 'sequence'
RETURN_KEY_PREDICTIONS = 'predictions'
RETURN_KEY_TARGETS = 'targets'
RETURN_KEY_MASK = 'mask'
