apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dallmann-aim-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: dallmann-aim-pv

