apiVersion: v1
kind: Service
metadata:
  name: aim-service
spec:
  selector:
    app: aim
  type: ClusterIP
  ports:
    - name: grpc
      port: 53800
      targetPort: 53800
      protocol: TCP
    - name: web
      port: 43800
      targetPort: 43800
      protocol: TCP