apiVersion: batch/v1
kind: Job
metadata:
  name: study-creator
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-database
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - -e
            - -x
            - |
              until pg_isready -U $(POSTGRES_USER) -h optuna-postgres -p 5432;
              do echo "waiting for postgres"; sleep 2; done;
          envFrom:
            - secretRef:
                name: optuna-postgres-secrets
      containers:
        - name: study-creator
          image: optuna/optuna:v2.5.0-py3.8-dev
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - -e
            - -x
            - |
              optuna create-study --skip-if-exists --direction maximize \
              --study-name "rnn-gru" --storage \
              "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@optuna-postgres:5432/${POSTGRES_DB}"
          envFrom:
            - secretRef:
                name: optuna-postgres-secrets