apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: optuna-postgres
  labels:
    app: optuna-postgres
spec:
  selector:
    matchLabels:
      app: optuna-postgres
  serviceName: optuna-postgres
  template:
    metadata:
      labels:
        app: optuna-postgres
    spec:
      containers:
        - name: optuna-postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: optuna-postgres-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: dallmann
            path: "/home/ls6/dallmann/optuna"
            secretRef:
              name: ceph-secret-dallmann